# GeoLite2 工作流配置文件
# 此文件包含工作流的可配置参数

# 数据库配置
databases:
  # 要下载的 GeoLite2 数据库类型
  types:
    - "GeoLite2-ASN"
    - "GeoLite2-Country"
  
  # MaxMind 下载 URL 模板
  download_url_template: "https://download.maxmind.com/app/geoip_download?edition_id={edition_id}&license_key={license_key}&suffix=tar.gz"

# 版本管理配置
version:
  # 版本号格式 (基于日期)
  format: "v{YYYYMMDD}"
  
  # 保留的历史版本数量
  keep_releases: 3
  
  # 版本检查方式
  check_method: "content_disposition"

# 文件处理配置
files:
  # 支持的归档格式
  archive_formats:
    - "tar.gz"
    - "zip"
  
  # 校验和算法
  checksum_algorithms:
    - "md5"
    - "sha256"
  
  # 工作目录
  directories:
    downloads: "downloads"
    releases: "releases"
    logs: "logs"

# 安全配置
security:
  # 工作流超时时间 (分钟)
  timeout_minutes: 30
  
  # 必需的 GitHub Secrets
  required_secrets:
    - "MAXMIND_LICENSE_KEY"
  
  # 最小权限设置
  permissions:
    contents: "write"
    actions: "read"
    security-events: "write"

# 调度配置
schedule:
  # Cron 表达式 (每周四 00:00 UTC)
  cron: "0 0 * * 4"
  
  # 时区
  timezone: "UTC"

# 通知配置
notifications:
  # 是否启用状态通知
  enabled: true
  
  # 通知级别
  levels:
    - "success"
    - "failure"
    - "cancelled"

# 日志配置
logging:
  # 日志级别
  level: "info"
  
  # 日志文件名格式
  filename_format: "update-{YYYYMMDD-HHMMSS}.log"
  
  # 是否保留日志文件
  keep_logs: false